apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-gen
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do for i in $(seq 1 50); do wget -q -O- http://34.169.98.220/ & done; sleep 0.1; done"]
        resources:
          requests:
            cpu: 50m
            memory: 32Mi