# Moderate Load Generator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-gen
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do for i in $(seq 1 50); do wget -q -O- http://hello-world/ & done; sleep 0.1; done"]
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
---
# Intensive Load Generator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intensive-load
spec:
  replicas: 5
  selector:
    matchLabels:
      app: intensive-load
  template:
    metadata:
      labels:
        app: intensive-load
    spec:
      containers:
      - name: load-gen
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do for i in $(seq 1 100); do wget -q -O- http://hello-world/ & done; sleep 0.01; done"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
---
# CPU Stress Generator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: stress
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do dd if=/dev/zero of=/dev/null & wget -q -O- http://hello-world/ & done"]
        resources:
          requests:
            cpu: 200m
            memory: 128Mi